# Generated by Django 4.2.13 on 2024-05-09 09:22

import apps.user.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import functools
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Họ và tên')),
                ('bio', models.CharField(blank=True, max_length=500, null=True, verbose_name='Bio')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, null=True, region=None, unique=True, verbose_name='Số điện thoại')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Tuổi')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Nam'), ('FEMALE', 'Nữ'), ('GAY', 'GAY'), ('LESBIAN', 'LESBIAN')], max_length=7, null=True, verbose_name='Giới tính')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Chiều cao')),
                ('weight', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cân nặng')),
                ('register_status', models.CharField(blank=True, choices=[('INFOR', 'INFOR'), ('SHARE', 'SHARE'), ('DONE', 'DONE')], max_length=5, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tham gia')),
                ('last_update', models.DateField(auto_now=True)),
                ('language_code', models.CharField(default='vi', max_length=30)),
                ('is_online', models.BooleanField(default=False)),
                ('is_busy', models.BooleanField(default=False)),
                ('is_live', models.BooleanField(default=False)),
                ('is_block', models.BooleanField(default=False)),
                ('is_fake', models.BooleanField(default=False)),
                ('follower', models.IntegerField(default=0)),
                ('following', models.IntegerField(default=0)),
                ('count_friend', models.IntegerField(default=0)),
                ('google_auth', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('apple_auth', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('agoraUID', models.TextField(blank=True, null=True)),
                ('stringeeUID', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verify', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Người dùng',
                'verbose_name_plural': 'Người dùng',
            },
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Tiêu đề')),
                ('introduce_content', models.TextField(blank=True, null=True, verbose_name='Nội dung giới thiệu')),
                ('terms_content', models.TextField(blank=True, null=True, verbose_name='Nội dung chính')),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/homecontent', verbose_name='Ảnh')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('SYSTEM', 'Hệ thống'), ('FRIEND', 'Bạn bè')], default='SYSTEM', max_length=6)),
                ('title', models.TextField(max_length=80, verbose_name='Tiêu đề')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Nội dung')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('custom_data', models.JSONField(blank=True, null=True)),
                ('direct_type', models.CharField(blank=True, max_length=100)),
                ('direct_value', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('direct_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to=functools.partial(apps.user.models.custom_media_file_path, *(), **{'path': 'media'}))),
                ('file_url', models.CharField(blank=True, max_length=500, null=True)),
                ('file_type', models.CharField(blank=True, choices=[('IMAGE', 'Ảnh'), ('VIDEO', 'Video'), ('AUDIO', 'Audio'), ('FILE', 'File')], max_length=500, null=True)),
                ('file_name', models.TextField(blank=True, default='', max_length=500, null=True)),
                ('file_extension', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.CharField(blank=True, max_length=500, null=True)),
                ('upload_finished_at', models.DateTimeField(blank=True, null=True)),
                ('file_duration', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('video_height', models.PositiveIntegerField(default=0)),
                ('video_width', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.fileupload'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
