# Generated by Django 4.2.11 on 2024-04-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Nam'), ('FEMALE', 'Nữ'), ('GAY', 'GAY'), ('LESBIAN', 'LESBIAN')], default='Unknown', max_length=7),
        ),
    ]
