# Generated by Django 4.2.11 on 2024-04-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='state_register',
            field=models.CharField(choices=[('INFOR', 'INFOR'), ('SHARE', 'SHARE'), ('DONE', 'DONE')], default='INFOR', max_length=5),
        ),
    ]
