# Generated by Django 4.2.11 on 2024-05-04 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_follow_fiendship_block_friendship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
