# Generated by Django 4.2.11 on 2024-04-02 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_state_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='state_register',
            new_name='register_status',
        ),
    ]
