# Generated by Django 4.2.3 on 2024-04-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_rename_state_register_customuser_register_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MALE", "Nam"),
                    ("FEMALE", "Nữ"),
                    ("GAY", "GAY"),
                    ("LESBIAN", "LESBIAN"),
                ],
                max_length=7,
                null=True,
            ),
        ),
    ]
