# Generated by Django 4.2.3 on 2024-04-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_customuser_is_coin_plan_profileimage"),
    ]

    operations = [
        migrations.RemoveField(model_name="customuser", name="is_coin_plan",),
    ]
