# Generated by Django 4.2.11 on 2024-05-06 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_category_remove_book_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='title111',
        ),
    ]
