# Generated by Django 4.2.3 on 2024-04-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_customuser_apple_auth_customuser_google_auth"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="baseinformation",
            options={"verbose_name": "Thông tin", "verbose_name_plural": "Thông tin"},
        ),
        migrations.AlterModelOptions(
            name="characterinformation",
            options={"verbose_name": "Tích cách", "verbose_name_plural": "Tích cách"},
        ),
        migrations.AlterModelOptions(
            name="communicateinformation",
            options={"verbose_name": "Nhu cầu", "verbose_name_plural": "Nhu cầu"},
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "Người dùng", "verbose_name_plural": "Người dùng"},
        ),
        migrations.AlterModelOptions(
            name="hobbyinformation",
            options={"verbose_name": "Sở thích", "verbose_name_plural": "Sở thích"},
        ),
        migrations.AlterModelOptions(
            name="searchinformation",
            options={"verbose_name": "Tìm kiếm", "verbose_name_plural": "Tìm kiếm"},
        ),
        migrations.AlterModelOptions(
            name="workinformation",
            options={
                "verbose_name": "Nghề nghiệp",
                "verbose_name_plural": "Nghề nghiệp",
            },
        ),
        migrations.AlterField(
            model_name="baseinformation",
            name="character",
            field=models.ManyToManyField(
                to="user.characterinformation", verbose_name="Tính cách"
            ),
        ),
        migrations.AlterField(
            model_name="baseinformation",
            name="communicate",
            field=models.ManyToManyField(
                to="user.communicateinformation", verbose_name="Nhu cầu"
            ),
        ),
        migrations.AlterField(
            model_name="baseinformation",
            name="hobby",
            field=models.ManyToManyField(
                to="user.hobbyinformation", verbose_name="Sở thích"
            ),
        ),
        migrations.AlterField(
            model_name="baseinformation",
            name="search",
            field=models.ManyToManyField(
                to="user.searchinformation", verbose_name="Tìm kiếm"
            ),
        ),
        migrations.AlterField(
            model_name="baseinformation",
            name="work",
            field=models.ManyToManyField(
                to="user.workinformation", verbose_name="Công việc"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Ngày sinh"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MALE", "Nam"),
                    ("FEMALE", "Nữ"),
                    ("GAY", "GAY"),
                    ("LESBIAN", "LESBIAN"),
                ],
                max_length=7,
                null=True,
                verbose_name="Giới tính",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="height",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Chiều cao"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="weight",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Cân nặng"
            ),
        ),
    ]
