# Generated by Django 4.2.11 on 2024-05-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_title_category_title111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title111',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
