# Generated by Django 4.2.3 on 2024-04-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_alter_friendship_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendship",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Đã gửi lời mời kết bạn"),
                    ("ACCEPTED", "Đang là bạn bè"),
                    ("REJECTED", "Từ chối kết bạn"),
                    ("DELETED", "Đã xóa"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
