# Generated by Django 4.2.3 on 2024-04-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0016_alter_friendship_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="age",
            field=models.IntegerField(blank=True, null=True, verbose_name="Tuổi"),
        ),
    ]
