# Generated by Django 4.2.3 on 2024-04-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0017_customuser_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="language_code",
            field=models.CharField(default="vi", max_length=30),
        ),
    ]
