# Generated by Django 4.2.3 on 2024-04-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0018_customuser_language_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseinformation",
            name="character",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="user.characterinformation",
                verbose_name="Tính cách",
            ),
        ),
        migrations.AlterField(
            model_name="baseinformation",
            name="communicate",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="user.communicateinformation",
                verbose_name="Nhu cầu",
            ),
        ),
        migrations.AlterField(
            model_name="baseinformation",
            name="hobby",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="user.hobbyinformation",
                verbose_name="Sở thích",
            ),
        ),
        migrations.AlterField(
            model_name="baseinformation",
            name="search",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="user.searchinformation",
                verbose_name="Tìm kiếm",
            ),
        ),
        migrations.AlterField(
            model_name="baseinformation",
            name="work",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="user.workinformation",
                verbose_name="Công việc",
            ),
        ),
    ]
