# Generated by Django 4.2.3 on 2024-04-16 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0019_alter_baseinformation_character_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseinformation",
            name="character",
            field=models.ManyToManyField(
                blank=True, to="user.characterinformation", verbose_name="Tính cách"
            ),
        ),
        migrations.AlterField(
            model_name="baseinformation",
            name="communicate",
            field=models.ManyToManyField(
                blank=True, to="user.communicateinformation", verbose_name="Nhu cầu"
            ),
        ),
        migrations.AlterField(
            model_name="baseinformation",
            name="hobby",
            field=models.ManyToManyField(
                blank=True, to="user.hobbyinformation", verbose_name="Sở thích"
            ),
        ),
        migrations.AlterField(
            model_name="baseinformation",
            name="search",
            field=models.ManyToManyField(
                blank=True, to="user.searchinformation", verbose_name="Tìm kiếm"
            ),
        ),
        migrations.AlterField(
            model_name="baseinformation",
            name="work",
            field=models.ManyToManyField(
                blank=True, to="user.workinformation", verbose_name="Công việc"
            ),
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("BLOCK", "Block"), ("UNBLOCK", "Unblock")],
                        default="BLOCK",
                        max_length=7,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "from_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_block",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_blocked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
