# Generated by Django 4.2.3 on 2024-04-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0023_alter_customuser_stringeeuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="stringeeUID",
            field=models.TextField(blank=True, null=True),
        ),
    ]
