"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-yd(2m=!pwsao811w41&2rj+q8*d*yd7^*p(4u7^ss!3mivbj2)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.user',
    'rest_framework',
    'django_api_admin',
    'corsheaders',
    # 'storages'
]

MIDDLEWARE = [
    "core.middleware.AddDataMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "apps.user.auth.JWTAuthentication",
        # 'rest_framework.authentication.SessionAuthentication'
    ]
}
#
# CORS_ORIGIN_ALLOW_ALL = True
#
# CORS_ALLOW_ALL_ORIGINS = True
# CORS_ALLOW_CREDENTIALS = True
# CORS_ALLOW_ALL_HEADERS = True
# CORS_ORIGIN_WHITELIST = [
#     'http://localhost',  # jest-dom test server
#     'http://localhost:3000',  # react developement server
#     'http://192.168.1.79:3000',
#     'https://django-bolt.vercel.app'
# ]
# Đặt CSRF_TRUSTED_ORIGINS thành ['*']
# CSRF_TRUSTED_ORIGINS = ['https://*.app', 'https://*.app', 'http://localhost', 'http://localhost:3000',
#                         'https://localhost:3000', 'https://localhost']
# CSRF_TRUSTED_ORIGINS = ['http://localhost:3000', 'http://192.168.1.79:3000', 'http://192.168.1.79:3000', 'http://192.168.1.55:3000',
#                         'http://192.168.1.55', 'https://django-bolt.vercel.app']
# CSRF_COOKIE_SAMESITE = None
# CSRF_COOKIE_DOMAIN = '.localhost'
# SESSION_COOKIE_DOMAIN = '.localhost'

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
AUTH_USER_MODEL = 'user.CustomUser'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Ho_Chi_Minh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Ho_Chi_Minh'

if os.getenv('USE_MINIO') == 'True':
    STORAGES = {
        "default": {"BACKEND": 'storages.backends.s3boto3.S3Boto3Storage'},
        "staticfiles": {"BACKEND": 'storages.backends.s3boto3.S3Boto3Storage'},
    }

    AWS_ACCESS_KEY_ID = os.getenv("MINIO_ROOT_USER")
    AWS_SECRET_ACCESS_KEY = os.getenv("MINIO_ROOT_PASSWORD")
    AWS_STORAGE_BUCKET_NAME = os.getenv("MINIO_BUCKET_NAME")
    AWS_S3_ENDPOINT_URL = os.getenv("MINIO_ENDPOINT")
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_FILE_OVERWRITE = False

OTP_PROVIDER_ID = os.getenv('OTP_PROVIDER_ID')
ZALO_OTP_URL = os.getenv('ZALO_OTP_URL')

STRINGEE_APP_ID = os.getenv("STRINGEE_APP_ID")
STRINGEE_APP_SECRET = os.getenv("STRINGEE_APP_SECRET")

SILKY_PYTHON_PROFILER = True
SILKY_AUTHENTICATION = True  # User must login
SILKY_AUTHORISATION = True  # User must have permissions
SILKY_META = True
SILKY_HIDE_SENSITIVE = False

SILKY_EXPLAIN_FLAGS = {'format':'JSON', 'costs': True}


CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_ALL_HEADERS = True
CORS_ORIGIN_WHITELIST = [
    'http://localhost',  # jest-dom test server
    'http://localhost:3000',  # react developement server
    'http://192.168.1.79:3000',
    'http://192.168.1.79',
    'http://192.168.1.55:3000',
    'http://192.168.1.55',
    'https://django-bolt.vercel.app',
    'https://django-bolt-git-main-andev916s-projects.vercel.app'
]

CORS_ALLOWED_ORIGINS = ['http://localhost:3000', 'http://192.168.1.79:3000', 'http://192.168.1.79:3000',
                        'http://192.168.1.55:3000',
                        'http://192.168.1.55', 'https://django-bolt.vercel.app',
                        'https://django-bolt-git-main-andev916s-projects.vercel.app']

CSRF_TRUSTED_ORIGINS = ['http://localhost:3000', 'http://192.168.1.79:3000', 'http://192.168.1.79:3000', 'http://192.168.1.55:3000',
                        'http://192.168.1.55', 'https://django-bolt.vercel.app', 'https://django-bolt-git-main-andev916s-projects.vercel.app', 'https://django-bolt.vercel.app/login']

# CSRF_COOKIE_DOMAIN = '.vercel.app'
# SESSION_COOKIE_DOMAIN = '.vercel.app'
# SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = None
CSRF_COOKIE_NAME = 'csrftoken'
# CSRF_COOKIE_HTTPONLY = True
# CSRF_USE_SESSIONS = True
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False  # Không yêu cầu cookie CSRF phải được gửi qua HTTPS

# CSRF_COOKIE_SECURE = False