# Generated by Django 4.2.3 on 2024-04-10 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("general", "0003_defaultavatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("MESSAGE", "Tin nhắn"), ("BLOG", "Bài viết")],
                        max_length=7,
                        null=True,
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Nội dung"
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Thiết lập ngày"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Cập nhật ngày"),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="general.fileupload",
                        verbose_name="Bằng chứng",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_sender",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Người gửi",
                    ),
                ),
                (
                    "verifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_verifier",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "Phản ánh", "verbose_name_plural": "Phản ánh",},
        ),
    ]
