# Generated by Django 4.2.3 on 2024-04-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0004_report"),
    ]

    operations = [
        migrations.RemoveField(model_name="report", name="image",),
        migrations.AddField(
            model_name="report",
            name="image",
            field=models.ManyToManyField(
                to="general.fileupload", verbose_name="Bằng chứng"
            ),
        ),
    ]
