# Generated by Django 4.2.3 on 2024-04-10 04:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("general", "0005_remove_report_image_report_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="verifier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_verifier",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
