# Generated by Django 4.2.3 on 2024-04-10 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0007_report_user_reported_alter_report_is_verified_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="report", name="user_reported",),
    ]
