# Generated by Django 4.2.3 on 2024-04-10 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("general", "0008_remove_report_user_reported"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="direct_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_receiver",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người bị tố cáo",
            ),
        ),
    ]
