# Generated by Django 4.2.3 on 2024-04-12 08:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("general", "0010_alter_fileupload_file_type"),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="file",
            field=models.ManyToManyField(blank=True, to="general.fileupload"),
        ),
        migrations.AlterField(
            model_name="blog",
            name="user_like",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="comment",
            name="file",
            field=models.ManyToManyField(blank=True, to="general.fileupload"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user_like",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="replycomment",
            name="user_like",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
