# Generated by Django 4.2.13 on 2024-05-09 08:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('SYSTEM', 'Hệ thống'), ('FRIEND', 'Bạn bè')], default='SYSTEM', max_length=6)),
                ('title', models.TextField(max_length=80, verbose_name='Tiêu đề')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Nội dung')),
                ('is_read', models.BooleanField(default=False, verbose_name='Đã đọc')),
                ('custom_data', models.JSONField(blank=True, null=True)),
                ('direct_type', models.CharField(blank=True, max_length=100)),
                ('direct_value', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Thông báo',
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(blank=True, max_length=200, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
