# Generated by Django 4.2.3 on 2024-03-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="custom_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
