# Generated by Django 4.2.3 on 2024-03-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0002_notification_custom_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
    ]
