# Generated by Django 4.2.3 on 2024-04-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0003_alter_notification_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"verbose_name": "Thông báo", "verbose_name_plural": "Thông báo"},
        ),
        migrations.AlterField(
            model_name="notification",
            name="body",
            field=models.TextField(blank=True, null=True, verbose_name="Nội dung"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="Đã đọc"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.TextField(max_length=80, verbose_name="Tiêu đề"),
        ),
    ]
