# Generated by Django 4.2.3 on 2024-04-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notification",
            "0004_alter_notification_options_alter_notification_body_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="body_en",
            field=models.TextField(blank=True, null=True, verbose_name="Nội dung"),
        ),
        migrations.AddField(
            model_name="notification",
            name="body_vi",
            field=models.TextField(blank=True, null=True, verbose_name="Nội dung"),
        ),
        migrations.AddField(
            model_name="notification",
            name="title_en",
            field=models.TextField(max_length=80, null=True, verbose_name="Tiêu đề"),
        ),
        migrations.AddField(
            model_name="notification",
            name="title_vi",
            field=models.TextField(max_length=80, null=True, verbose_name="Tiêu đề"),
        ),
    ]
