# Generated by Django 4.2.3 on 2024-04-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0005_notification_body_en_notification_body_vi_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(default="SYSTEM", max_length=6),
        ),
    ]
