# Generated by Django 4.2.3 on 2024-04-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0006_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[("SYSTEM", "Hệ thống"), ("FRIEND", "Bạn bè")],
                default="SYSTEM",
                max_length=6,
            ),
        ),
    ]