# Generated by Django 4.2.3 on 2024-04-05 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("general", "0003_defaultavatar"),
        ("conversation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        default="waiting", max_length=10, verbose_name="Trạng thái"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("call", "Cuộc gọi thoại"),
                            ("video", "Cuộc gọi video"),
                        ],
                        default="call",
                        max_length=10,
                        verbose_name="Loại",
                    ),
                ),
                (
                    "last",
                    models.CharField(
                        default="", max_length=255, verbose_name="Thời gian cuộc gọi"
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Thời gian bắt đầu"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Thời gian kết thúc"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="RoomUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HOST", "Chủ nhóm"),
                            ("KEY", "Phó nhóm"),
                            ("USER", "Thành viên"),
                        ],
                        max_length=4,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="message",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TEXT", "Văn bản"),
                    ("AUDIO", "Âm thanh"),
                    ("VIDEO", "Video"),
                    ("IMAGE", "Hình ảnh"),
                    ("GIFT", "Quà tặng"),
                    ("CALL", "Gọi"),
                ],
                max_length=5,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RANDOM", "Ngẫu nhiên"),
                            ("PRIVATE", "Ẩn danh"),
                            ("CONNECT", "Thông thường"),
                            ("GROUP", "Nhóm"),
                            ("NOTIFICATION", "Thông báo"),
                        ],
                        max_length=12,
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Tên phòng"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="general.fileupload",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlockChat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "user_block",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_block",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_blocked",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_blocked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="message",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="conversation.room",
            ),
        ),
    ]
