# Generated by Django 4.2.3 on 2024-04-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "conversation",
            "0002_call_roomuser_alter_message_type_room_blockchat_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
