# Generated by Django 4.2.3 on 2024-04-05 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("conversation", "0003_message_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomuser",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="conversation.room",
                verbose_name="Phòng",
            ),
        ),
        migrations.AddField(
            model_name="roomuser",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Thành viên",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="conversation.room",
                verbose_name="Phòng",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Người gửi",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Tiêu đề"
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TEXT", "Văn bản"),
                    ("AUDIO", "Âm thanh"),
                    ("VIDEO", "Video"),
                    ("IMAGE", "Hình ảnh"),
                    ("GIFT", "Quà tặng"),
                    ("CALL", "Gọi"),
                ],
                max_length=5,
                null=True,
                verbose_name="Loại",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RANDOM", "Ngẫu nhiên"),
                    ("PRIVATE", "Ẩn danh"),
                    ("CONNECT", "Thông thường"),
                    ("GROUP", "Nhóm"),
                    ("NOTIFICATION", "Thông báo"),
                ],
                max_length=12,
                null=True,
                verbose_name="Loại phòng",
            ),
        ),
        migrations.AlterField(
            model_name="roomuser",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HOST", "Chủ nhóm"),
                    ("KEY", "Phó nhóm"),
                    ("USER", "Thành viên"),
                ],
                max_length=4,
                null=True,
                verbose_name="Chức danh",
            ),
        ),
    ]
