# Generated by Django 4.2.3 on 2024-04-05 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "conversation",
            "0004_roomuser_room_roomuser_user_alter_message_room_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="call",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="conversation.call",
            ),
        ),
    ]
