# Generated by Django 4.2.3 on 2024-04-09 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0007_room_is_accepted"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="is_leaved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="room",
            name="newest_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="roomuser",
            name="date_removed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
