# Generated by Django 4.2.3 on 2024-04-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0008_room_is_leaved_room_newest_at_roomuser_date_removed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TEXT", "Văn bản"),
                    ("AUDIO", "Âm thanh"),
                    ("VIDEO", "Video"),
                    ("IMAGE", "Hình ảnh"),
                    ("GIFT", "Quà tặng"),
                    ("CALL", "Gọi"),
                    ("HISTORY", "Lịch sử"),
                ],
                max_length=7,
                null=True,
                verbose_name="Loại",
            ),
        ),
    ]
