# Generated by Django 4.2.3 on 2024-04-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0009_alter_message_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomuser",
            name="last_active",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
