# Generated by Django 4.2.3 on 2024-04-10 03:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0010_roomuser_last_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomuser",
            name="last_active",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2024, 4, 10, 10, 40, 15, 857477),
            ),
            preserve_default=False,
        ),
    ]
