# Generated by Django 4.2.3 on 2024-04-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0011_alter_roomuser_last_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="call",
            name="type",
            field=models.CharField(
                choices=[("CALL", "Cuộc gọi thoại"), ("VIDEO", "Cuộc gọi video")],
                default="call",
                max_length=10,
                verbose_name="Loại",
            ),
        ),
    ]
