# Generated by Django 4.2.3 on 2024-04-12 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0010_alter_fileupload_file_type"),
        ("conversation", "0012_alter_call_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="general.fileupload",
                verbose_name="Ảnh",
            ),
        ),
    ]
