# Generated by Django 4.2.3 on 2024-04-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0013_alter_room_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TEXT", "Văn bản"),
                    ("AUDIO", "Âm thanh"),
                    ("VIDEO", "Video"),
                    ("IMAGE", "Hình ảnh"),
                    ("FILE", "File"),
                    ("GIFT", "Quà tặng"),
                    ("CALL", "Gọi"),
                    ("HISTORY", "Lịch sử"),
                ],
                max_length=7,
                null=True,
                verbose_name="Loại",
            ),
        ),
    ]
