# Generated by Django 4.2.3 on 2024-05-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0017_alter_message_text_alter_room_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="newest_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
