# Generated by Django 4.2.3 on 2024-04-03 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveStreamingHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CHAT", "Chat"),
                            ("AUDIO", "Audio"),
                            ("STREAM", "Stream"),
                        ],
                        max_length=6,
                        null=True,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("duration", models.IntegerField(default=0)),
                ("user_view", models.IntegerField(default=0)),
                ("gift", models.IntegerField(default=0)),
                ("comment", models.IntegerField(default=0)),
                ("coin", models.IntegerField(default=0)),
                ("diamond", models.IntegerField(default=0)),
                ("start_time", models.CharField(max_length=100)),
                ("cover_image", models.CharField(max_length=255)),
                ("profile_image", models.CharField(max_length=255)),
                ("end_time", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LiveView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("profile_image", models.CharField(max_length=255)),
                ("agora_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "live_streaming",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discovery.livestreaminghistory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LiveUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("profile_image", models.CharField(max_length=255)),
                ("cover_image", models.CharField(max_length=255)),
                ("dob", models.CharField(max_length=100)),
                ("token", models.CharField(max_length=255)),
                ("channel", models.CharField(max_length=255)),
                ("coin", models.IntegerField(default=0)),
                ("diamond", models.IntegerField(default=0)),
                ("agora_uid", models.IntegerField(default=0)),
                ("view", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "live_streaming",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discovery.livestreaminghistory",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
