# Generated by Django 4.2.11 on 2024-04-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0002_alter_livestreaminghistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveuser',
            name='view',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
