# Generated by Django 4.2.3 on 2024-04-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0003_alter_liveuser_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="livestreaminghistory",
            name="is_hide",
            field=models.BooleanField(default=False),
        ),
    ]
