# Generated by Django 4.2.3 on 2024-04-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discovery", "0004_livestreaminghistory_is_hide"),
    ]

    operations = [
        migrations.AddField(
            model_name="livestreaminghistory",
            name="province",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
