# Generated by Django 4.2.3 on 2024-05-02 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0014_rename_video_duration_fileupload_file_duration"),
        ("discovery", "0005_livestreaminghistory_province"),
    ]

    operations = [
        migrations.AddField(
            model_name="livestreaminghistory",
            name="side",
            field=models.CharField(
                choices=[
                    ("BAC", "Miền bắc"),
                    ("TRUNG", "Miền trung"),
                    ("NAM", "Miền nam"),
                    ("--", "--"),
                ],
                default="--",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="liveview",
            name="last_join",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="livestreaminghistory",
            name="country",
            field=models.CharField(
                choices=[("VN", "Toàn quốc"), ("--", "--")],
                default="--",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="livestreaminghistory",
            name="cover_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="general.fileupload"
            ),
        ),
    ]
