# Generated by Django 4.2.3 on 2024-05-02 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("general", "0014_rename_video_duration_fileupload_file_duration"),
        ("discovery", "0006_livestreaminghistory_side_liveview_last_join_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livestreaminghistory",
            name="cover_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="general.fileupload",
            ),
        ),
    ]
