# Generated by Django 4.2.3 on 2024-05-06 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("discovery", "0010_remove_livestreaminghistory_end_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=15)),
                ("image", models.ImageField(upload_to="assets/image/gift")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("STAR", "STAR"),
                            ("DIAMOND", "DIAMOND"),
                            ("ROSE", "ROSE"),
                            ("DONUT", "DONUT"),
                        ],
                        default="STAR",
                        max_length=7,
                    ),
                ),
                ("price", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="messagelive",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("TEXT", "Văn bản"),
                    ("AUDIO", "Âm thanh"),
                    ("VIDEO", "Video"),
                    ("IMAGE", "Hình ảnh"),
                    ("FILE", "File"),
                    ("GIFT", "Quà tặng"),
                    ("CALL", "Gọi"),
                    ("VIDEO_CALL", "Gọi"),
                    ("HISTORY", "Lịch sử"),
                ],
                max_length=10,
                null=True,
                verbose_name="Loại",
            ),
        ),
        migrations.CreateModel(
            name="GiftLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.IntegerField(default=1)),
                ("total_price", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="discovery.gift"
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="messagelive",
            name="gift_log",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="discovery.giftlog",
            ),
        ),
    ]
